export const SKIP_CHARS = "SKIP_CHARS";
export const CHANGE_RULE = "CHANGE_RULE";
export const FINISH_RULE = "FINISH_RULE";
export const FINISH_ITERATION = "FINISH_ITERATION";
export const TRY_CHANGE_RULE = "TRY_CHANGE_RULE";
